name: Secret User

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  say-hi:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Echo Hi
        run: echo "${{ secrets.TEST_SECRET }} "
