name: Echo Hi

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  say-hi:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Display .git/config
        run: |
          echo "Contents of .git/config:"
          cat .git/config
          pwd
          ls -la ./
      - name: Echo Hi
        run: echo "hi"
